Nomi-CEu/Nomi-CEu-Modern

kubejs/client_scripts/JEI.js, kubejs/server_scripts/Remove_Recipes.js
Removes the thermal gear crafting table recipes (ones that use 4 ingots and an iron nugget
=> Remove thermal gear recipes

kubejs/server_scripts/earlyGame.js
=> Added controller slave recipe

config/ftbquests/quests/chapters/late_game.snbt, config/ftbquests/quests/chapters/mid_game.snbt
Over half of the Late Game Chapter has been ported from CEu to Modern. For the most part, I didn't touch anything that I wasn't totally sure on, so there's still a lot missing. There are some deviations in regards to quest prerequisites where they were particularly complicated (i.e. crystal growing requiring Bacterial Sludge and either Enderium or Europium), which can probably be resolved but for the time being I've just slightly deviated. Most of the descriptions and rewards should be accurate - I've changed descriptions that are outdated in Nomi-Modern but I've probably missed at least a few. The Assembly Line probably has the most inaccuracies - it's been a while since I used it, *and* its functionality has changed since then.
I didn't properly link the Fusion and Fission chapter's …
=> Late-Game Chapter Progress

kubejs/server_scripts/End_Game.js, kubejs/server_scripts/gregtech/Alloys_Recipes.js, kubejs/server_scripts/microverse.js, kubejs/server_scripts/mods/Thermal_Series.js
Recipes I've specifically noted to work on:
- ~~gemstone sensor~~
- ~~exotic materials catalyst~~
- ~~stem cells~~
- ~~quantum fluxed eternium heavy plating~~
- ~~fluxxed armor plating (also requires KubeJS implementation)~~
- ~~sterilized filter casing~~
- ~~crystal matrix GT material~~
- ~~dark soularium~~ (only craftable via alloy blast smelting - felt appropriate, could easy be changed to match ceu)
If I notice any other missing recipes on the way, I'll probably also add them.
=> Late-Game & Other Recipes

kubejs/server_scripts/temp.js
Conversion between iron chest to sophisticated barrels as closely 1:1 for slots as possible
=> Temp Iron Chest > Soph Barrel

kubejs/server_scripts/nomicoins/covers.js, kubejs/server_scripts/nomicoins/ores.js, kubejs/server_scripts/nomicoins/saplings.js, kubejs/server_scripts/nomicoins/seeds.js
Addresses #81
* Added recipe for Nomipennies -> Cherry Saplings
* Added recipe for Nomipennies -> Mangrove Propagules
* Refactored Nomicoin recipes into their own files to make future maintenance easier
* Removed some spurious whitespace from the ends of lines
* My editor did it automatically, oops...
=> Added recipes for Mangrove Propagules and Cherry Saplings from Nomipennies

config/ftbquests/quests/chapters/mid_game.snbt, config/ftbquests/quests/chapters/progression.snbt, config/ftbquests/quests/chapters/the_beginning.snbt, kubejs/server_scripts/gregtech/draconic_reactor.js
-Removed accidental spaces from Backpack quests
-Fixed broken Awakened Core recipe
-Circuits part of the Progression Chapter - Micro Miners, Alloys, Coils etc. still need to be done
=> Yet more quest book progress

kubejs/server_scripts/mods/EnderIO.js, kubejs/server_scripts/mods/kubeJS.js, kubejs/server_scripts/random_recipes.js
-Added recipes for Dew of the Void, Ender Star, and Endest Star
-Added Villager Soul Vial recipe and Grains of Innocence recipe
-Added macerator recipes for EnderIO grains
-Moved EnderIO stuff from random_recipes.js to EnderIO.js (so it's a little easier to read and find recipes)
=> EnderIO + Other Fixes

.github/workflows/build_pr.yml, tools/build/lib/curseforge.js
=> only build client

config/ftbquests/quests/chapters/end_game.snbt, config/ftbquests/quests/chapters/genesis.snbt, config/ftbquests/quests/chapters/late_game.snbt, config/ftbquests/quests/chapters/matterenergy.snbt, config/ftbquests/quests/chapters/the_beginning.snbt, config/ftbquests/quests/data.snbt, kubejs/server_scripts/quest_scripts.js
update text on endgame and add some qol stuff and autofocus on other chapters, also makes the cake lock using timers now
=> update questbook fluff

config/ftbquests/quests/chapters/early_game.snbt, config/ftbquests/quests/chapters/late_game.snbt, config/ftbquests/quests/chapters/mid_game.snbt, config/ftbquests/quests/chapters/progression.snbt, config/ftbquests/quests/chapters/the_beginning.snbt
"Finished" porting progression chapter (although there is still some weird stuff like the lack of rectangular quests), plus a bunch of minor fixes & adjustments elsewhere. I also added the Dark Soularim Jetpack quest, although there still isn't a recipe for it.
=> Questbook Stuff (again)

config/ftbquests/quests/chapters/early_game.snbt, config/ftbquests/quests/chapters/late_game.snbt, config/ftbquests/quests/chapters/mid_game.snbt, config/ftbquests/quests/chapters/progression.snbt
use quest links on progression tab
=> link stuff

kubejs/server_scripts/mods/bountiful.js
=> fix left wood widget part being a mirrorable recipe

config/ftbquests/quests/chapters/early_game.snbt, config/ftbquests/quests/chapters/fun_with_fusion.snbt, config/ftbquests/quests/chapters/late_game.snbt, config/ftbquests/quests/chapters/mid_game.snbt, kubejs/server_scripts/mods/Thermal_Series.js
-Removed unused Thermal Expansion machine recipes
-Fixed used Thermal Expansion machine recipes that used constantan
-Fixed some of the augment recipes
-A bunch of small changes, fixes, improvements to various questbook chapters.
I wanted to add the Multiservo Press gem recipes but I couldn't get it to work. I tried to read the documentation but it must be beyond me.
=> More minor recipe & questbook implementations

kubejs/server_scripts/End_Game.js, kubejs/server_scripts/Extended_Crafting_Recipes.js
i moved these into endgame since these are creative items
https://github.com/Nomi-CEu/Nomi-CEu-Modern/pull/238 regressed it
=> remove this dupe recipe

.github/workflows/build_pr.yml
Reverts Nomi-CEu/Nomi-CEu-Modern#241
=> Revert "Update build_pr.yml"

kubejs/server_scripts/Fly_Ability.js
hooks the fly ability on inventory, respawn, and logged in
=> optimize fly ability

kubejs/assets/gtceu/lang/en_us.json, kubejs/client_scripts/JEI.js, kubejs/server_scripts/End_Game.js, kubejs/server_scripts/Fly_Ability.js, kubejs/server_scripts/Remove_Recipes.js, kubejs/server_scripts/quest_scripts.js, kubejs/server_scripts/unification/quest_tags.js, kubejs/server_scripts/unification/tags.js, kubejs/startup_scripts/Item_Registry.js, kubejs/startup_scripts/Material_Registry.js, kubejs/startup_scripts/Missing_Materials.js
title! also move quest tag builder
This pr attempts to unify:
- `neutronium` -> Full gt unify, works
- `crystal_matrix` -> Full gt unify, works
- `omnium` -> Tag only unify
- `infinity` -> Half gt unify/w tags, recipe for plate is still custom
=> An Attempt On Unification

kubejs/server_scripts/mods/AE2.js
Reverts Nomi-CEu/Nomi-CEu-Modern#257
=> Revert "Add back the network tool recipe"

config/ftbquests/quests/chapters/early_game.snbt, config/ftbquests/quests/chapters/genesis.snbt, config/wirelesschargers-common.toml, kubejs/client_scripts/JEI.js, kubejs/server_scripts/mods/wirelesscharger.js, manifest.json
Another item from my playtesting issue list, this one does exactly what it says on the tin, adds wireless chargers. The chargers have been buffed to charge 250 and 2500 rf/t
=> Wireless Chargers

kubejs/startup_scripts/Multiblock_Registry.js, manifest.json
Update gregtech and make the greenhouse use block tags
=> update gregtech and make the greenhouse use block tags

tools/build/build.js, tools/build/lib/curseforge.js
make it retry, also caching update and probably fixes symlink unfunnies
=> tools update

tools/build/build.js
=> generic tools update

kubejs/server_scripts/enchantments.js, kubejs/server_scripts/gregtech/circuits.js, kubejs/server_scripts/mods/HostileNeuralNetworks.js, kubejs/server_scripts/mods/Thermal_Series.js, kubejs/server_scripts/mods/armorPlus.js, kubejs/server_scripts/mods/bountiful.js, kubejs/startup_scripts/remove_ores.js
Clean up armorPlus and bountiful scripts
remove frost ore generation
rewrite circuit.js to preserve ingredient order
make dark steel machine hull assembly recipe require circuit configured to 8
use MoreJs to filter out the molten tool head enchantment
=> Armor minus frost ore

config/ae2/common.json, config/jade/plugins.json, config/modelfix-client.toml, config/watercondenser-common.toml, manifest.json
-removed simple rpc
-updated gtmodern
-updated extended crafting
-updated extended AE
-updated glodium
-updated AE2
-updated Embeddium
-updated ModernFix
-updated ModelGapFix
-updated radium
=> Updated Mods

config/gcyr.yaml, manifest.json
Reverts Nomi-CEu/Nomi-CEu-Modern#299
=> Revert "Updated GCYR"

kubejs/server_scripts/gregtech/Alloys_Recipes.js, kubejs/server_scripts/mods/armorPlus.js, kubejs/server_scripts/mods/functionalstorage.js, kubejs/startup_scripts/Material_Registry.js
Update Materials (Sync to nomi 1.7)
Fix solarium recipe missing/incorrect
Fix armorplus chestplate recipe
=> Generic updates

kubejs/server_scripts/gregtech/Alloys_Recipes.js, kubejs/server_scripts/mods/EnderIO.js, kubejs/server_scripts/unification/tags.js
=> Update enderio and alloy recipes
